name: Deploy to Staging

on:
  push:
    branches: [develop]

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run type-check

      - name: Lint check
        run: pnpm run lint:check

      - name: Build for staging
        run: pnpm run build
        env:
          VITE_APP_ENV: staging

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Notify deployment
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Vercel Preview deployment successful!"
            echo "🔗 Preview URL will be available in Vercel dashboard"
          else
            echo "❌ Vercel Preview deployment failed!"
          fi
